### ISSUE TITLE
android 下给图片设置高度100% 出错

### ISSUE THREAD

**Issue by mishe** [mishe/blog#31]
开发手机大图浏览插件过程中，发现：

给图片设定 

``` css
css({width:'auto',height:'100%'});
```

但设置

``` css
css({width:'100%',height:'auto'});
```

会造成出错

必须写成：

``` javascript
var h=$(window).height()
```

``` css
css({width:'auto',height:h});
```

可以修改以上的BUG
