### ISSUE TITLE
CSS3圆环倒计时效果;可设置步长和停止角度(转自个人百度空间)

### ISSUE THREAD

**Issue by mishe** [mishe/blog#35]
## css 内容

``` css
        .pie { width:200px; height:200px; background-color:blue; border-radius:100px; position:absolute; }
        .pie1 { clip:rect(0px,200px,200px,100px); -o-transform:rotate(0deg); -moz-transform:rotate(0deg); -webkit-transform:rotate(0deg); background:-moz-radial-gradient(20% 50% 0deg, #333, #0000ff); background:-webkit-gradient(radial, 100 100, 0, 100 100, 110, from(#000), to(#0000ff)); }
        .pie2 { clip:rect(0px,100px,200px,0px); -o-transform:rotate(0deg); -moz-transform:rotate(0deg); -webkit-transform:rotate(0deg); background:-moz-radial-gradient(80% 50% 0deg, #333, #0000ff); background:-webkit-gradient(radial, 100 100, 0, 100 100, 110, from(#000), to(#0000ff)); }
        .hold { width:200px; height:200px; position:absolute; z-index:1; }
        .hold1 { clip:rect(0px,200px,200px,100px); }
        .hold2 { clip:rect(0px,100px,200px,0px); }
        .bg { width:200px; height:200px; background-color:red; border-radius:100px; position:absolute; box-shadow:0px 0px 8px #333; background:-moz-radial-gradient(0% 50% 0deg, #900, #ff0000); background:-webkit-gradient(radial, 100 100, 0, 100 100, 110, from(#900), to(#ff0000)); }
        .time { width:160px; height:160px; margin:20px 0 0 20px; background-color:#fff; border-radius:100px; position:absolute; z-index:1; box-shadow:0px 0px 8px #333 inset; text-align:center; line-height:160px; font-family:"Book Antiqua", Palatino, serif; font-size:35px; font-weight:bold; text-shadow: 1px 1px 3px #333; }
        .time em { background:#fff; position:absolute; top:62px; left:12px; height:18px; width:140px; opacity:0.4; }
```
## html 结构内容

``` html
<div class="hold hold1">
    <div class="pie pie1" id="pie1"></div>
</div>
<div class="hold hold2">
    <div class="pie pie2" id="pie2"></div>
</div>
<div class="bg"> </div>
<div class="time"><span></span><em></em></div>
```
## js实现脚本

依赖jquery

``` javascript
(function(step,total){
    var count= 0,pos=0;
    function start1(){
        count += step;
        count=count>=total?total:count;
        if(count<=180){
            $(".pie1").css("-o-transform","rotate(" + count + "deg)");
            $(".pie1").css("-moz-transform","rotate(" + count + "deg)");
            $(".pie1").css("-webkit-transform","rotate(" + count + "deg)");
            if(count>=total){
                return;
            }
        }else if(count<360){
            if(!pos){
                $(".pie1").css("-o-transform","rotate(" + 180 + "deg)");
                $(".pie1").css("-moz-transform","rotate(" + 180 + "deg)");
                $(".pie1").css("-webkit-transform","rotate(" + 180 + "deg)");
                pos=1;
            }
            $(".pie2").css("-o-transform","rotate(" + (count-180) + "deg)");
            $(".pie2").css("-moz-transform","rotate(" + (count-180) + "deg)");
            $(".pie2").css("-webkit-transform","rotate(" + (count-180) + "deg)");
            if(count>=total){
                return;
            }
        }else{
            $(".pie2").css("-o-transform","rotate(" + 180 + "deg)");
            $(".pie2").css("-moz-transform","rotate(" + 180 + "deg)");
            $(".pie2").css("-webkit-transform","rotate(" + 180 + "deg)");
        }
        if(count<360){
            setTimeout(start1,100);
        }
    }
    start1();
})(11,100)
```
