### ISSUE TITLE
移动开发碰到的问题

### ISSUE THREAD

**Issue by mishe** [mishe/blog#51]
## 自动大写与自动修正

要关闭这两项功能，可以通过autocapitalize 与autocorrect 这两个选项：

``` html
<input type="text" autocapitalize="off" autocorrect="off" />
```
## 使用特殊链接：

如果你关闭自动识别后 ，又希望某些电话号码能够链接到 iPhone 的拨号功能 ，那么可以通过这样来声明电话链接 ,

``` html
<a href="tel:12345654321">打电话给我</a>
<a href="sms:12345654321">发短信</a>
```
## 强制竖屏

``` html
<meta name="screen-orientation" content="portrait"><!-- uc强制竖屏 -->
<meta name="x5-orientation" content="portrait"><!-- QQ强制竖屏 -->
```
## 解决触屏端的滚动问题

``` css
-webkit-overflow-scrolling: touch;
```
## 多行...

``` css
overflow:hidden;
text-overflow:ellipsis;
white-space:nowrap;
-webkit-line-clamp:2
```
## 解决点击区域闪的情况

``` css
-webkit-tap-highlight-color: rgba(0,0,0,0);
```
## 隐藏地址栏 & 处理事件的时候，防止滚动条出现：

``` javascript
addEventListener('load', function(){
        setTimeout(function(){ window.scrollTo(0, 1); }, 100);
});
```
## 阻止旋转屏幕时自动调整字体大小

``` css
html, body, form, fieldset, p, div, h1, h2, h3, h4, h5, h6 {-webkit-text-size-adjust:none;}
```
## 消除transition闪屏

``` css
-webkit-transform-style: preserve-3d;
/*设置内嵌的元素在 3D 空间如何呈现：保留 3D*/
-webkit-backface-visibility:hidden;
/*（设置进行转换的元素的背面在面对用户时是否可见：隐藏）*/
```

禁止ios弹出各种操作窗口

``` css
-webkit-touch-callout:none
```

禁止用户选中文字

``` css
-webkit-user-select:none
```
## andriod上去掉语音输入按钮

``` css
input::-webkit-input-speech-button {display: none}
```
